/* Editorial content is dated; no fabricated prices or automatic trading signals. */
(() => {
  'use strict';
  const ir='https://investor.nvidia.com/financial-info/quarterly-results/default.aspx';
  const sources={dsx:'https://blogs.nvidia.com/blog/dsx-ready-ai-factories-power-cooling/',robot:'https://blogs.nvidia.com/blog/isaac-ros-5-0-agentic-open-source-robotics/',rubin:'https://blogs.nvidia.com/blog/vera-rubin-nvl72-mlperf-inference/',rsi:'https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/RSI',macd:'https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/macd'};
  const link=(url,label)=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
  const section=(id,kicker,title,desc,body)=>`<section id="${id}" class="section shell research"><div class="section-heading"><div><p class="eyebrow">${kicker}</p><h2>${title}</h2></div><p>${desc}</p></div>${body}</section>`;
  const card=(title,text)=>`<article class="panel"><h3>${title}</h3><p>${text}</p></article>`;
  document.querySelector('.hero').insertAdjacentHTML('afterend',section('learn','START HERE / 研究使用指南','先用三分鐘讀懂 NVIDIA','先問需求從哪來，再問設備何時交付，最後才問價格是否已反映期待。',`
  <div class="notice"><strong>資料狀態｜研究整理：2026-09-24</strong><br>下方原有財報圖表截至 FY2026，屬歷史基準，並非最新季度。新聞為逐篇人工整理；行情依 TradingView 顯示時間與權限，可能延遲。技術檢核需自行核對，沒有背景自動判斷。</div>
  <div class="research-grid">${card('01｜它賣什麼？','不只是顯示卡。AI 資料中心需要 GPU 運算、CPU 協調、網路傳輸與軟體工具。可把 NVIDIA 想成提供整套 AI 工廠設備與開發工具的平台商；系統價值不等於單顆晶片售價。')}${card('02｜誰付錢？','雲端服務商、企業、研究機構與各國算力建設計畫購買設備或雲端算力。終端 AI 使用量增加不會立即等比例變成 NVIDIA 營收：中間還有預算、融資、交貨及驗收。')}${card('03｜股價為何不同步？','營收成長回答「公司賺更多了嗎」；估值回答「市場已付多少期待」。即使財報成長，若低於預期或未來回報下降，股價仍可能下跌。好產品不等於任何價格都值得買。')}</div>
  <details><summary>訓練、推論、CUDA：用白話串起商業模式</summary><p>訓練像讀書建立能力，推論像每次回答問題。訓練常需要大量同步運算；推論更關注延遲、記憶體與每次回答成本。CUDA 是讓開發者使用 GPU 的軟體工具生態；既有程式與開發經驗提高轉換成本，但不能據此假設競爭永遠無法追上。</p><p>更高效率可能降低單次任務所需硬體，也可能讓更多任務變得划算。究竟是節省設備還是擴大需求，要追蹤總使用量與客戶投資報酬，而非只看一項跑分。</p></details>
  <details><summary>五分鐘閱讀路線</summary><ol><li>看行情時間與財報期間，先排除過期資料。</li><li>讀事件卡的「事實」，不要把公司目標當已達成結果。</li><li>沿供應鏈找限制：晶片、記憶體、機櫃、電力哪一項拖延？</li><li>用收入、毛利、現金流與客戶投資回報交叉驗證。</li><li>最後檢查趨勢、波動、事件風險及假設失效條件。</li></ol></details>`));
  document.querySelector('#supply-chain').insertAdjacentHTML('beforeend',`<div class="research"><div class="notice">供應鏈地圖是產業角色示意，不能視為所有公司均已取得某一代 NVIDIA 產品訂單。HBM 認證、封裝合作、份額與交付時間須逐代確認；「通過認證」也不等於營收。</div><div class="table-wrap"><table><thead><tr><th>環節與白話介紹</th><th>如何影響 NVIDIA</th><th>可觀察證據</th><th>容易誤讀的地方</th></tr></thead><tbody>
  <tr><td>晶圓製造｜在矽晶圓上製造電路</td><td>良率和可分配產能影響 GPU 供給；有晶圓還不代表有可交付整機。</td><td>代工廠法說的先進製程需求、資本支出與產能爬坡。</td><td>全公司資本支出不等於 NVIDIA 專用產能。</td></tr>
  <tr><td>先進封裝｜把運算晶片與記憶體連在一起</td><td>封裝產出不足時，前段晶圓增加也未必提高出貨。</td><td>實際量產時間、良率、基板及測試供給。</td><td>宣布擴廠不等於當季可用產能；不同封裝方案不可直接相加。</td></tr>
  <tr><td>HBM｜靠近 GPU 的高速記憶體</td><td>容量與頻寬影響效能；價格上漲可能提高系統成本。</td><td>供應商對各代 HBM 認證、量產與銷售的正式說明。</td><td>SK hynix、Micron、Samsung 為產業參與者示例，非所有平台已認證名單。</td></tr>
  <tr><td>網通｜讓 GPU 一起工作</td><td>擴大叢集後，交換器、互連與光連接成為效能及成本變數。</td><td>網通收入、系統配置、叢集利用率與客戶實際測試。</td><td>GPU 數量不能直接換算有效運算量。</td></tr>
  <tr><td>機櫃／液冷／電力｜讓設備能真正運作</td><td>散熱、供電、機房工程限制可能延後部署。</td><td>已通電容量、客戶驗收、散熱設備交期。</td><td>規劃中的 MW 不是已上線 MW；設計容量不是實際利用量。</td></tr>
  <tr><td>雲端與企業｜把算力變成服務</td><td>客戶回報影響下一輪採購；自研 ASIC 在特定工作負載構成競爭。</td><td>客戶現金流、CapEx、AI 收入、利用率與推論成本。</td><td>CapEx 包含土地、建物等，不全是 GPU 訂單；AI 收入揭露口徑也不同。</td></tr></tbody></table></div><p class="muted">本表為機制分析，不含未經證實的供應商訂單或市占數字。查證入口：${link(ir,'NVIDIA 季度文件')}、${link('https://investor.tsmc.com/english/quarterly-results','TSMC 法說資料')}。</p></div>`);
  document.querySelector('#watchlist').insertAdjacentHTML('beforebegin',section('events','CONTEXT / 事件消化','新聞如何傳到損益表？','以下是選讀事件，不是完整新聞流。官方來源也可能帶有行銷角度；推論不代表公司指引。',`
  <div class="research-grid">
  <article class="panel event"><span class="tag">2026-09-21 · 基礎設施</span><h3>DSX Ready：從晶片延伸到電力與冷卻</h3><p><strong>事實：</strong>NVIDIA 推出 DSX Ready 資格認定計畫，初期涵蓋電池儲能與冷卻液分配設備。</p><p><strong>可能影響：</strong>AI 工廠的交付限制不限於 GPU；配套工程會影響客戶何時可使用算力。</p><p><strong>反方檢查：</strong>資格認定不是採購訂單，也不能代替個別場址的工程驗證。</p><p><strong>後續看：</strong>已通電容量、交付與驗收進度，而非只數合作夥伴。</p>${link(sources.dsx,'NVIDIA 官方原文')}</article>
  <article class="panel event"><span class="tag">2026-09-16 · 系統效能</span><h3>Vera Rubin：跑分之後要看使用成本</h3><p><strong>事實：</strong>NVIDIA 公布 Vera Rubin NVL72 的 MLPerf Inference 預覽結果，宣稱特定測試吞吐量最高為 GB300 NVL72 的 3.7 倍。</p><p><strong>可能影響：</strong>若實際部署也提高效率，客戶每次推論的成本可能下降。</p><p><strong>反方檢查：</strong>預覽結果不是所有模型的效能保證，也不是已大量交付的證據。</p><p><strong>後續看：</strong>模型、精度、延遲、功耗、售價與供貨條件能否同口徑比較。</p>${link(sources.rubin,'NVIDIA 官方原文')}</article>
  <article class="panel event"><span class="tag">2026-09-22 · 機器人</span><h3>Isaac ROS 5.0：先看採用，再看收入</h3><p><strong>事實：</strong>NVIDIA 推出開源 Isaac ROS 5.0，提供 GPU 加速機器人開發套件與開發工作流程。</p><p><strong>可能影響：</strong>工具採用可能促進邊緣運算設備需求，但商業轉換需要時間。</p><p><strong>反方檢查：</strong>下載量、展示影片或開發者人數不等於付費訂單。</p><p><strong>後續看：</strong>量產專案、模組出貨及可辨識收入；不把機器人視為已獨立揭露的財報分部。</p>${link(sources.robot,'NVIDIA 官方原文')}</article></div>
  <details><summary>政策與競爭新聞怎麼讀？</summary><p>出口政策需要查生效日期、產品範圍、許可條件與實際出貨，而不是沿用舊禁令摘要。本站沒有提供即時法規判定。ASIC 則要分工作負載：固定用途的成本優勢不代表可替代所有 GPU 工作；也不能忽略大型客戶有降低供應商依賴的動機。</p></details>`));
  document.querySelector('#financials').insertAdjacentHTML('beforeend',`<div class="research"><div class="notice">財報閱讀界線：上方 FY26 為歷史基準。完整最新季度請到 ${link(ir,'官方季度資料')} 核對，不以本站靜態圖表代表最新財報。</div><div class="research-grid two">
  ${card('營收與指引：結果和預期要分開','營收是已認列的業績；管理層指引是對未來的估計。比較時要用同一季度、同一幣別與同一會計口徑。年增率看長期擴張，季增率看近期節奏；高基期可能使年增率放慢，即使收入仍增加。')}
  ${card('毛利率：每 100 元收入剩多少？','毛利率扣除銷售成本，但尚未扣研發、行銷等費用。新品組合、記憶體成本、良率與價格都會影響它。年度 71.1% 不能直接和單季數字視為同一期間比較；GAAP 與調整後數字也要分開。')}
  ${card('現金流：獲利有沒有變成現金？','一起看營業現金流、應收帳款和存貨。如果收入成長但收款放慢，應追查客戶付款與認列條件。自由現金流常以營業現金流減資本支出計算，跨公司比較前須核對定義。')}
  ${card('估值：市場要求多快的未來？','本益比＝股價 ÷ 每股盈餘；預估本益比使用尚未實現的預測，因此會隨分析師修正而變。成長快不保證估值合理；要問若成長或毛利低於期待，原先假設是否仍成立。本站不提供即時本益比或目標價。')}
  </div><details><summary>每次財報的七個問題</summary><ol><li>收入成長來自出貨量、價格還是產品組合？</li><li>資料中心與網通的成長是否一致？</li><li>毛利變化是一次性費用還是持續成本？</li><li>存貨、應收款與現金流是否相互吻合？</li><li>客戶集中度與採購承諾風險如何變化？</li><li>新產品交付是否符合之前時程？</li><li>下一季指引有哪些尚未驗證的前提？</li></ol></details></div>`);
  const indicators=[['SMA 20 / 50 / 200','最近 N 個收盤價的平均；20、50、200 日常用來分辨短、中、長期趨勢。','看價格位置與均線斜率；多頭排列仍可能遇到急跌。均線滯後，震盪時容易反覆穿越。'],['RSI 14','衡量近期上漲與下跌力度，介於 0–100。常見 70 / 30 作為過熱／過冷參考。','強趨勢中可長時間偏高或偏低。超買不等於立刻賣，超賣不等於底部。'],['MACD 12 / 26 / 9','12 期 EMA 減 26 期 EMA；訊號線為 MACD 的 9 期 EMA。柱狀圖是兩者差值。','交叉提示動能改變，不保證趨勢反轉。與均線同源，不能當完全獨立的第二份證據。'],['成交量與相對量','比較當日成交量與之前 20 個完整交易日均量。','尚未收盤時直接比全日均量會失真；突破放量也可能是消息後的拋售換手。'],['ATR 14','用真實波幅的平滑平均衡量波動，包含跳空影響。','ATR 不判斷方向；波動增加時，同一股數會承擔更大價格風險。'],['支撐／壓力與相對強度','用前高、前低及成交密集區觀察供需；相對強度可看 NVDA / QQQ 或半導體指數比值。','支撐不是保證承接。比值上升表示相對較強，不一定代表股價本身上漲；它也不是 RSI。']];
  document.querySelector('#market').insertAdjacentHTML('afterend',section('technical','TECHNICAL / 方法與風險','技術分析：用來描述，不用來預言','本站不宣稱 NVDA 現在超買、突破或形成買點。先確認交易日、時區、復權方式與完整收盤資料。',`
  <div class="notice">圖表預設 MA 不保證是 50 日：請在 TradingView 指標設定確認週期，並自行加入 20 / 50 / 200 日線。日 K 與週 K 的「50 期」不同；下方原有勾選框是你的手動紀錄，不是系統判定。</div>
  <div class="research-grid two">${indicators.map(([t,d,c])=>card(t,`${d}<br><br><strong>如何避免誤用：</strong>${c}`)).join('')}</div><p class="muted">指標說明參考：${link(sources.rsi,'Fidelity RSI')} · ${link(sources.macd,'Fidelity MACD')}。參數為常見設定，不是最佳化結果。</p>
  <details><summary>三種情境：把觀察、確認與失效條件寫清楚</summary><div class="table-wrap"><table><thead><tr><th>情境</th><th>觀察與確認</th><th>失效或需重評估</th></tr></thead><tbody><tr><td>趨勢延續</td><td>長期均線向上；短期回落後，價格與成交量是否恢復？</td><td>價格跌破先前假設的重要區間；基本面同時轉差。</td></tr><tr><td>區間突破</td><td>先定義區間，再看收盤、成交量及後續數個交易日，而非只看盤中越線。</td><td>快速回到區間，或放量卻無法延續。</td></tr><tr><td>財報跳空</td><td>先讀財報與指引，再評估跳空是否改變波動與原始假設。</td><td>停損價未必成交；流動性不足時損失可能超出計畫。</td></tr></tbody></table></div></details>
  <div class="panel"><h3>部位風險試算｜手動輸入，不連接交易</h3><p>用同一幣別填入資金與價格。此工具只做算術，不推薦進場價、停損價或風險比例。</p><form id="riskForm"><div class="research-grid"><label>可用資金（USD）<input id="capital" type="number" min="0.01" step="any" required placeholder="例如 10000"></label><label>單筆計畫風險（%）<input id="riskPct" type="number" min="0.01" max="100" step="any" required placeholder="自行設定"></label><label>假設進場價（USD）<input id="entryPrice" type="number" min="0.01" step="any" required></label><label>假設停損價（USD）<input id="stopPrice" type="number" min="0.01" step="any" required></label></div><button type="submit">計算整股上限</button><output id="riskResult" aria-live="polite">尚未輸入；沒有使用 NVDA 即時價格。</output></form><p class="muted">僅適用不融資的股票多單。股數＝向下取整 min（資金 × 風險比例 ÷ 每股價差，資金 ÷ 進場價）。未計手續費、匯率、稅與滑價；跳空可能使實際虧損超過計畫。</p></div>`));
  const glossary=[['HBM','高頻寬記憶體，幫 GPU 快速取得資料；不等同一般 DDR 記憶體。'],['CoWoS','TSMC 的先進封裝技術家族，將運算晶片與記憶體等整合；不是製程節點名稱。'],['CapEx','資本支出，用來購建長期資產；雲端公司的 CapEx 不全流向 NVIDIA。'],['CSP / Hyperscaler','雲端服務供應商／超大規模雲端業者，是大型算力採購方。'],['ODM / OEM','代工設計製造商／品牌設備商，參與系統設計、組裝與交付。'],['ASP','平均售價，受產品组合影響；高 ASP 不必然代表同一產品漲價。'],['TCO','總持有成本，包括設備、電力、冷卻、維運與使用效率。'],['Token','模型處理文字等資料的單位；每 token 成本比較要固定模型與品質條件。'],['ASIC','特定用途晶片，為某類工作設計；彈性與效率的取捨和 GPU 不同。'],['GAAP / Non-GAAP','會計準則報表／公司調整後指標；調整項目需要逐一核對。'],['FY / YoY / QoQ','會計年度／年增率／季增率。NVIDIA 會計年度不等於同名曆年。'],['Design win','設計採用，表示被選入產品方案；不等於量產收入或保證採購。']];
  document.querySelector('main').insertAdjacentHTML('beforeend',section('glossary','REFERENCE / 隨查隨讀','名詞字典與資料邊界','搜尋中英文縮寫，先理解概念再解讀新聞。',`<label for="termSearch">搜尋名詞</label><input class="search" id="termSearch" type="search" placeholder="例如 HBM、資本支出、毛利"><div id="terms" class="research-grid two">${glossary.map(([t,d])=>card(t,d)).join('')}</div><p id="termStatus" aria-live="polite"></p><div class="notice"><strong>這個網站能做與不能做的事</strong><br>能做：整理研究框架、提供來源、互動圖表、手動紀錄與風險算術。不能做：保證即時行情、自動更新財報、驗證供應商所有訂單、預測價格或執行交易。未串接券商、付費資料 API 或帳戶資訊。筆記只在目前瀏覽器儲存，清除網站資料會遺失；第三方圖表與字型會向其服務商發送請求。</div>`));
  document.querySelector('nav').insertAdjacentHTML('beforeend','<a href="#learn">入門</a><a href="#events">時事</a><a href="#technical">技術解讀</a><a href="#glossary">字典</a>');
  document.querySelector('.thesis-card').innerHTML='<div class="thesis-head"><span>研究假設 · 待持續驗證</span><span class="status">MONITOR</span></div><p>AI 設備需求能否轉成持續收入，取決於客戶回報、供應鏈交付與新產品成本。這是研究問題，不是即時評分或買賣建議。</p><div class="signal-row"><span>需求</span><strong>追蹤客戶 CapEx 與回報</strong></div><div class="signal-row"><span>供給</span><strong>核對交付與驗收</strong></div><div class="signal-row"><span>價格</span><strong>檢查已反映的期待</strong></div>';
  document.getElementById('termSearch').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();let n=0;document.querySelectorAll('#terms article').forEach(el=>{el.hidden=!el.textContent.toLowerCase().includes(q);if(!el.hidden)n++;});document.getElementById('termStatus').textContent=`顯示 ${n} 個名詞`;});
  document.getElementById('riskForm').addEventListener('submit',e=>{e.preventDefault();const [c,r,p,s]=['capital','riskPct','entryPrice','stopPrice'].map(id=>Number(document.getElementById(id).value));const out=document.getElementById('riskResult');if(![c,r,p,s].every(Number.isFinite)||c<=0||r<=0||r>100||p<=0||s<=0||s>=p){out.textContent='請輸入有效正數；多單停損價必須低於進場價，風險比例不得超過 100%。';return;}const n=Math.floor(Math.min(c*r/100/(p-s),c/p));out.textContent=`算術上限 ${n.toLocaleString()} 股｜投入 $${(n*p).toFixed(2)}｜按停損價成交的計畫損失 $${(n*(p-s)).toFixed(2)}。非建議部位。`;});
})();
